local L = {}
L.UPDATE = {}
L.UPDATE.COPY_RIGHT ="Copyright (c) 2024 OpenPoker Technology CO., LTD All Rights Reserved."
L.UPDATE.CHECKING_VERSION ="संस्करण की जांच रहा है।"--正在检查版本
L.UPDATE.CHECKING_RES_UPDATE ="संसाधन अपडेट के लिए जांच रहा है"--正在检查资源更新
L.UPDATE.DOWNLOADING_MSG ="संसाधन डाउनलोड कर रहा है।({1}/{2})"--正在下载资源({1}/{2})
L.UPDATE.UPDATE_NOW ="अब अपडेट करें"--现在更新
L.UPDATE.UPDATE_LATER ="बाद में अपडेट करें"--以后更新
L.UPDATE.DOWNLOAD_ERROR ="डाउनलोड में त्रुटि होता है।"--下载出错
L.UPDATE.DOWNLOAD_NOT_IN_WIFI_PROMPT_TITLE ="सूचना"--温馨提示
L.UPDATE.SPEED ="डाउनलोड गति：{1}"--下载速度：{1}
L.UPDATE.DOWNLOAD_NOT_IN_WIFI_PROMPT_MSG ="वर्तमान में आप उपयोग किया जा रहा नेटवर्क wifi नहीं है। आपको {1} के अपडेट पैकेज डाउनलोड करने के लिए अपना मोबाइल ट्रैफ़िक खर्च करना होगा। क्या इसे तुरंत डाउनलोड किया गया है?"--您当前使用的网络不是wifi,需要耗费您的手机流量下载{1}的更新包，是否立即下载？
L.UPDATE.UPDATE_COMPLETE ="अपडेट पूरा हुआ है।"--更新完成
L.UPDATE.IS_ALREADY_THE_LATEST_VERSION ="सब से नया संस्करण गै।"--已经是最新版本
L.UPDATE.BAD_NETWORK_MSG ="खराब नेटवर्क स्थिति से अपडेट पर विफल है।"--网络状况不佳，更新失败
L.UPDATE.UPDATE_CANCELED ="अपडेट रद्द कर दिया गया है।"--更新已经取消
L.UPDATE.DOWNLOAD_SIZE ="डाउनलोड प्रपत्र नाप：{1}"--下载文件大小：{1}
L.UPDATE.DOWNLOAD_PROGRESS =" {1}% संसाधन डाउनलोड कर रहा है"--正在下载资源 {1}%
L.UPDATE.QUIT_DIALOG_TITLE ="लॉगआउट की पुष्टि करेंगे"--确认退出
L.UPDATE.QUIT_DIALOG_MSG ="सची है？लॉगआउट की पुष्टि करेंगे।"--真的确认退出游戏吗？\\(≧▽≦)/~
L.UPDATE.QUIT_DIALOG_CONFIRM ="सची है।"--忍痛退出
L.UPDATE.QUIT_DIALOG_CANCEL ="नहीं।"--我点错了
return L