local K = {}

K.AUTO_BUY_IN = "AUTO_BUY_IN"
K.AUTO_SIT    = "AUTO_SIT"
K.SHOCK       = "SHOCK"
K.VOLUME      = "VOLUME"
K.CHATVOICE	  = "CHATVOICE"

K.LAST_LOGIN_TYPE              = "LAST_LOGIN_TYPE"
K.LOGIN_MTKEY                  = "LOGIN_MTKEY"
K.LOGINED_DEVICE               = "LOGINED_DEVICE"
K.USER_FIRST_DEALER_SEND_CHIP  = "USER_FIRST_DEALER_SEND_CHIP"  --用户第一次给荷官送筹码
K.FACEBOOK_ACCESS_TOKEN        = "FACEBOOK_ACCESS_TOKEN"
K.LINE_ACCESS_TOKEN        	   = "LINE_ACCESS_TOKEN"

K.FACEBOOK_RECALLED_NAMES       = "FACEBOOK_RECALLED_NAMES"
K.YESTERDAY_RECALLED_NAMES      = "YESTERDAY_RECALLED_NAMES"
K.THIRDDAY_RECALLED_NAMES       = "THIRDDAY_RECALLED_NAMES"

K.FACEBOOK_INVITED_NAMES       = "FACEBOOK_INVITED_NAMES"
K.YESTERDAY_INVITED_NAMES      = "YESTERDAY_INVITED_NAMES"
K.THIRDDAY_INVITED_NAMES       = "THIRDDAY_INVITED_NAMES"

K.FACEBOOK_INVITED_PAGE        = "FACEBOOK_INVITED_PAGE"
K.FACEBOOK_TODAY_INVITE_MONEY  = "FACEBOOK_TODAY_INVITE_MONEY"  -- 当天邀请奖励记录
K.RECORD_SEND_DEALER_CHIP_TIME = "RECORD_SEND_DEALER_CHIP_TIME" -- 记录给荷官送筹码的次数
K.DALIY_REPORT_INVITABLE       = "DALIY_REPORT_INVITABLE"       -- 记录每日是否已经上报能邀请的用户数
K.LOGIN_UIDS                   = "LOGIN_UIDS"                   -- 登录uid列表

K.DALIY_REPORT_OLDUSER_INVITED = "DALIY_REPORT_OLDUSER_INVITED" -- 记录每日使用邀请老用户的功能时间

K.GTF_GUIDE_TO_FACEBOOK        = 'GTF_GUIDE_TO_FACEBOOK'        -- 是否已经引导过facebook登录
K.GTF_CHECK_TODAY              = 'GTF_CHECK_TODAY'              -- 今天是否已经检查过
K.GTF_LOGIN_COUNT              = 'GTF_LOGIN_COUNT'              -- 使用游客登录的次数

K.TIPS_STATE                   = 'TIPS_STATE'                   -- 提示标识

K.QT_NEXT_DAY_CHIPS_TYPE       = 'QT_NEXT_DAY_CHIPS_TYPE'       -- 明天再来可以领取的奖励类型
K.QT_NEXT_DAY_CHIPS_REWARD     = 'QT_NEXT_DAY_CHIPS_REWARD'     -- 明天再来可以领取的奖励数量

-- 推送消息 自动召回参数
K.RN_HAVEAUTORECALL = 'RN_HAVEAUTORECALL' -- bool值, 通知native层写,Lua层读/写
K.RN_AUTORECALL_MSG = 'RN_AUTORECALL_MSG' -- json串, 包含 key chip 必选字段

-- 邀请数量记录的日期
K.FB_LAST_INVITE_DAY       = 'FB_LAST_INVITE_DAY' -- os.date(fmt)返回的字符串

-- 今日已邀请数量
K.FB_INVITE_FRIENDS_NUMBER = 'FB_INVITE_FRIENDS_NUMBER' -- int

--好友召回
K.FB_LAST_RECALL_DAY = 'FB_LAST_RECALL_DAY' -- int
K.FB_RECALL_FRIENDS_NUMBER = 'FB_RECALL_FRIENDS_NUMBER' -- int

K.IOS_ORDER_INFO = "IOS_ORDER_INFO" -- IOS订单信息

K.LOGIN_USER_LEVEL = "LOGIN_USER_LEVEL" -- 登陆时玩家的等级

K.FRIENDS_FULL_TIPS    = 'FRIENDS_FULL_TIPS'                   -- 好友已满提示

K.BG_SOUND = "BG_SOUND"

K.CARD_POWER_TIPS = "CARD_POWER_TIPS" --牌力指示器
K.CUR_LANGUAGE = "CUR_LANGUAGE" --当前语言

K.TEXAS_ROOM_TYPE = "TEXAS_ROOM_TYPE" -- 选择的德州游戏场次类型
K.TEXAS_ROOM_FAST = "TEXAS_ROOM_FAST" -- 选择的德州游戏快速场
K.TEXAS_ROOM_NUM = "TEXAS_ROOM_NUM" -- 选择的德州游戏场人数

K.LEVEL_CONFIGU_URL = "LEVEL_CONFIGU_URL" -- 等级配置

K.IS_SHOW_LINE_REWARD = "IS_SHOW_LINE_REWARD" -- 是否显示line首次登录奖励

K.IS_FINISHED_PUSH_TASK = "IS_FINISHED_PUSH_TASK_" -- 今天是否完成了打开推送任务

K.GUEST_BIND_TYPE = "GUEST_BIND_TYPE" -- 游客绑定的账号类型
return K
