local E = {}

E.APP_ENTER_BACKGROUND = "APP_ENTER_BACKGROUND"
E.APP_ENTER_FOREGROUND = "APP_ENTER_FOREGROUND"

E.HALL_LOGIN_SUCC       = "HALL_LOGIN_SUCC"
E.HALL_LOGOUT_SUCC      = "HALL_LOGOUT_SUCC"
E.HALL_SHOW_MAIN_HALL   = "HALL_SHOW_MAIN_HALL"
E.HALL_SHOW_CHOOSE_ROOM = "HALL_SHOW_CHOOSE_ROOM"
E.ENTER_ROOM_WITH_DATA  = "ENTER_ROOM_WITH_DATA"
E.LOGIN_ROOM_SUCC       = "LOGIN_ROOM_SUCC"
E.LOGIN_ROOM_FAIL       = "LOGIN_ROOM_FAIL"
E.ROOM_CONN_PROBLEM     = "ROOM_CONN_PROBLEM"
E.SERVER_STOPPED        = "SERVER_STOPPED"
E.LOGOUT_ROOM_SUCC      = "LOGOUT_ROOM_SUCC"

E.UI_TAB_CHANGE = "UI_TAB_CHANGE"

E.SEND_DEALER_CHIP_BUBBLE_VIEW = "SEND_DEALER_CHIP_BUBBLE_VIEW"
E.SVR_BROADCAST_ACT_STATE      = "SVR_BROADCAST_ACT_STATE" -- 活动完成
E.SVR_BROADCAST_ADD_EXP        = "SVR_BROADCAST_ADD_EXP"   -- 加经验动画
E.UPDATE_SEAT_ANTE_CHIP        = "UPDATE_SEAT_ANTE_CHIP"   -- 更新携带

E.SHOW_EXIST_PASSWORD_ICON = "SHOW_EXIST_PASSWORD_ICON"

E.SVR_BROADCAST_BIG_LABA = "SVR_BROADCAST_BIG_LABA" --大喇叭消息

E.HIDE_GIFT_POPUP        = "HIDE_GIFT_POPUP"        -- 关闭礼物弹框
E.GET_CUR_SELECT_GIFT_ID = "GET_CUR_SELECT_GIFT_ID" -- 获取当前礼物ID

E.UPDATE_CUR_SELECT_GIFT_ID = "UPDATE_CUR_SELECT_GIFT_ID" --更新礼物ID

E.DOUBLE_LOGIN_LOGINOUT = "DOUBLE_LOGIN_LOGINOUT" -- 账号同时登录时退出消息

E.SVR_ERROR = "SVR_ERROR"

-- 积分商城
E.SCORE_MARKET_EXCHANGE = "SCORE_MARKET_EXCHANGE" -- 积分兑换
--点对点邀请好友
E.UPDATE_SEAT_INVITE_VIEW = "UPDATE_SEAT_INVITE_VIEW"

E.UPDATE_SEAT_PUSH_VIEW = "UPDATE_SEAT_PUSH_VIEW"  --推送召回

E.UPDATE_SEAT_INVITE_PLAY_VIEW = "UPDATE_SEAT_INVITE_PLAY_VIEW"--邀请进入房间一起玩牌

E.CHOOSEARENA_PLAY_HIDE_ANIM = "CHOOSEARENA_PLAY_HIDE_ANIM"

E.ENABLED_EDITBOX_TOUCH = "ENABLED_EDITBOX_TOUCH" --打开输入框触摸事件

E.DISENABLED_EDITBOX_TOUCH = "DISENABLED_EDITBOX_TOUCH" --关闭输入框触摸事件

E.LOGIN_HALL_SVR_SUCC = "LOGIN_HALL_SVR_SUCC"  -- 登录普通房间server成功
-- 比赛相关事件
E.MATCH_LOGIN_ROOM_SUCC = "MATCH_LOGIN_ROOM_SUCC" -- 登录比赛房间成功
E.MATCH_LOGIN_ROOM_FAIL = "MATCH_LOGIN_ROOM_FAIL" -- 登录比赛房间失败
E.MATCH_SVR_ERROR = "MATCH_SVR_ERROR" 			  -- 比赛服务器异常
E.LOGIN_MATCH_HALL_SVR_SUCC = "LOGIN_MATCH_HALL_SVR_SUCC"  -- 登录比赛房间server成功
E.MATCH_START_LOGIN = "MATCH_START_LOGIN" -- 比赛开始登陆
-- 私人房和搜索房间
E.PRIVATE_CREAT_RESULT = "PRIVATE_CREAT_RESULT" -- 私人房创建结果
E.SEARCH_ROOM_RESULT = "SEARCH_ROOM_RESULT" -- 私人房创建结果
E.PRIVATE_ROOM_LIST = "PRIVATE_ROOM_LIST" -- 私人房列表
-- 玩家支付情况
E.USER_PAY_INFO_CHANGE = "USER_PAY_INFO_CHANGE" -- 玩家支付信息变化
-- 玩家支付成功 
E.USER_PAY_SUCCESS = "USER_PAY_SUCCESS" -- 充值成功

E.USER_FIRST_PAY_SUCCESS = "USER_FIRST_PAY_SUCCESS" --首充支付成功

-- 玩家资产变化
E.USER_PROPERTY_CHANGE = "USER_PROPERTY_CHANGE" -- PHP交互资产变化

E.TASK_REWARD_POINT = "TASK_REWARD_POINT" -- 任务奖励提示点

E.UPDATE_FREE_CHIP_VIEW_RED_STATE = "UPDATE_FREE_CHIP_VIEW_RED_STATE" --大转盘红点提示

E.UPDATE_FRIEND_DATA = "UPDATE_FRIEND_DATA" --更新好友数据，当在好友界面，好友关注或取消的时候，刷新好友列表数据

E.KEYBOARD_POPUP_ENTER = "KEYBOARD_POPUP_ENTER" --自定义键盘回车键事件

E.KEYBOARD_POPUP_NUM_CHANGED = "KEYBOARD_POPUP_NUM_CHANGED" --自定义键盘数字改变

E.REMOVE_OTHER_KEYBOARD_POPUP = "REMOVE_OTHER_KEYBOARD_POPUP" --删除其他键盘，一个界面同时存在多个输入框的时候，只会显示一个

E.REDBLACK_ALL_PLAYER_LIST = "REDBLACK_ALL_PLAYER_LIST" --红黑所有玩家列表

E.UPDATE_GOLD_ISLAND_POOL = "UPDATE_GOLD_ISLAND_POOL" --更新夺金岛奖池

E.UPDATE_GOLD_ISLAND_BUY_STATUS = "UPDATE_GOLD_ISLAND_BUY_STATUS" --更新夺金岛购买按钮状态

E.UPDATE_GOLD_ISLAND_AUTO_BUY_STATUS = "UPDATE_GOLD_ISLAND_AUTO_BUY_STATUS" --更新夺金岛自动购买按钮状态

E.SHOW_GOLD_ISLAND_REWARD = "SHOW_GOLD_ISLAND_REWARD" --显示夺金岛中奖

E.UPDATE_PLAY_CARD_STATUS = "UPDATE_PLAY_CARD_STATUS" --更新玩牌活动按钮状态

E.UPDATE_COUNTRY = "UPDATE_COUNTRY" --更新国籍

return E
